using EPiServer.Framework.Localization;

namespace EditorPowertools.Localization;

/// <summary>
/// Provides all JavaScript UI strings from the localization service,
/// serialized to window.EPT_STRINGS in the layout.
/// </summary>
public class UiStringsProvider(LocalizationService loc)
{
    private string S(string key) => loc.GetString($"/editorpowertools/ui/{key}");

    public object GetAll() => new
    {
        shared = new
        {
            loading = S("shared/loading"),
            noresults = S("shared/noresults"),
            cancel = S("shared/cancel"),
            apply = S("shared/apply"),
            close = S("shared/close"),
            runnow = S("shared/runnow"),
            refresh = S("shared/refresh"),
            starting = S("shared/starting"),
            export = S("shared/export"),
            prev = S("shared/prev"),
            next = S("shared/next"),
            yes = S("shared/yes"),
            no = S("shared/no"),
            open = S("shared/open"),
            all = S("shared/all"),
            save = S("shared/save"),
            delete = S("shared/delete"),
            edit = S("shared/edit"),
            failed = S("shared/failed")
        },
        contentaudit = new
        {
            col_contentid = S("contentaudit/col_contentid"),
            col_name = S("contentaudit/col_name"),
            col_language = S("contentaudit/col_language"),
            col_contenttype = S("contentaudit/col_contenttype"),
            col_maintype = S("contentaudit/col_maintype"),
            col_url = S("contentaudit/col_url"),
            col_editurl = S("contentaudit/col_editurl"),
            col_breadcrumb = S("contentaudit/col_breadcrumb"),
            col_status = S("contentaudit/col_status"),
            col_createdby = S("contentaudit/col_createdby"),
            col_created = S("contentaudit/col_created"),
            col_changedby = S("contentaudit/col_changedby"),
            col_changed = S("contentaudit/col_changed"),
            col_published = S("contentaudit/col_published"),
            col_publisheduntil = S("contentaudit/col_publisheduntil"),
            col_masterlanguage = S("contentaudit/col_masterlanguage"),
            col_alllanguages = S("contentaudit/col_alllanguages"),
            col_referencecount = S("contentaudit/col_referencecount"),
            col_versioncount = S("contentaudit/col_versioncount"),
            col_haspersonalizations = S("contentaudit/col_haspersonalizations"),
            filter_all = S("contentaudit/filter_all"),
            filter_pages = S("contentaudit/filter_pages"),
            filter_blocks = S("contentaudit/filter_blocks"),
            filter_media = S("contentaudit/filter_media"),
            filter_unpublished = S("contentaudit/filter_unpublished"),
            filter_unused = S("contentaudit/filter_unused"),
            op_contains = S("contentaudit/op_contains"),
            op_equals = S("contentaudit/op_equals"),
            op_startswith = S("contentaudit/op_startswith"),
            op_isempty = S("contentaudit/op_isempty"),
            op_isnotempty = S("contentaudit/op_isnotempty"),
            btn_filter = S("contentaudit/btn_filter"),
            btn_columns = S("contentaudit/btn_columns"),
            btn_selectall = S("contentaudit/btn_selectall"),
            btn_reset = S("contentaudit/btn_reset"),
            btn_addfilter = S("contentaudit/btn_addfilter"),
            btn_clearall = S("contentaudit/btn_clearall"),
            dlg_choosecolumns = S("contentaudit/dlg_choosecolumns"),
            dlg_addfilter = S("contentaudit/dlg_addfilter"),
            lbl_column = S("contentaudit/lbl_column"),
            lbl_operator = S("contentaudit/lbl_operator"),
            lbl_value = S("contentaudit/lbl_value"),
            lbl_filtervalue = S("contentaudit/lbl_filtervalue"),
            lbl_search = S("contentaudit/lbl_search"),
            stat_totalitems = S("contentaudit/stat_totalitems"),
            stat_pages = S("contentaudit/stat_pages"),
            stat_currentpage = S("contentaudit/stat_currentpage"),
            empty_nodata = S("contentaudit/empty_nodata"),
            empty_nofilter = S("contentaudit/empty_nofilter"),
            page_showing = S("contentaudit/page_showing"),
            perpage = S("contentaudit/perpage"),
            fmt_excel = S("contentaudit/fmt_excel"),
            fmt_csv = S("contentaudit/fmt_csv"),
            fmt_json = S("contentaudit/fmt_json"),
            cell_openeditmode = S("contentaudit/cell_openeditmode")
        },
        languageaudit = new
        {
            tab_overview = S("languageaudit/tab_overview"),
            tab_missing = S("languageaudit/tab_missing"),
            tab_stale = S("languageaudit/tab_stale"),
            tab_queue = S("languageaudit/tab_queue"),
            stat_totalcontent = S("languageaudit/stat_totalcontent"),
            stat_languages = S("languageaudit/stat_languages"),
            stat_missing = S("languageaudit/stat_missing"),
            stat_stale = S("languageaudit/stat_stale"),
            stat_itemstotranslate = S("languageaudit/stat_itemstotranslate"),
            stat_page = S("languageaudit/stat_page"),
            stat_missing_lang = S("languageaudit/stat_missing_lang"),
            stat_stale_count = S("languageaudit/stat_stale_count"),
            card_coverage = S("languageaudit/card_coverage"),
            card_contentitems = S("languageaudit/card_contentitems"),
            card_published = S("languageaudit/card_published"),
            lbl_language = S("languageaudit/lbl_language"),
            lbl_threshold = S("languageaudit/lbl_threshold"),
            lbl_targetlang = S("languageaudit/lbl_targetlang"),
            lbl_contenttype = S("languageaudit/lbl_contenttype"),
            lbl_alllanguages = S("languageaudit/lbl_alllanguages"),
            lbl_alltypes = S("languageaudit/lbl_alltypes"),
            btn_coveragetree = S("languageaudit/btn_coveragetree"),
            btn_apply = S("languageaudit/btn_apply"),
            btn_exportcsv = S("languageaudit/btn_exportcsv"),
            btn_runnow = S("languageaudit/btn_runnow"),
            btn_started = S("languageaudit/btn_started"),
            btn_failed = S("languageaudit/btn_failed"),
            col_id = S("languageaudit/col_id"),
            col_name = S("languageaudit/col_name"),
            col_type = S("languageaudit/col_type"),
            col_master = S("languageaudit/col_master"),
            col_available = S("languageaudit/col_available"),
            col_location = S("languageaudit/col_location"),
            col_masterlanguage = S("languageaudit/col_masterlanguage"),
            col_stalelanguage = S("languageaudit/col_stalelanguage"),
            col_daysbehind = S("languageaudit/col_daysbehind"),
            col_lastupdated = S("languageaudit/col_lastupdated"),
            col_available_short = S("languageaudit/col_available_short"),
            empty_all_translated = S("languageaudit/empty_all_translated"),
            empty_no_stale = S("languageaudit/empty_no_stale"),
            empty_no_queue = S("languageaudit/empty_no_queue"),
            empty_no_tree = S("languageaudit/empty_no_tree"),
            empty_nodata = S("languageaudit/empty_nodata"),
            banner_runjob = S("languageaudit/banner_runjob"),
            page_info = S("languageaudit/page_info"),
            btn_previous = S("languageaudit/btn_previous"),
            btn_next = S("languageaudit/btn_next")
        },
        cmsdoctor = new
        {
            header_title = S("cmsdoctor/header_title"),
            header_desc = S("cmsdoctor/header_desc"),
            lbl_lastrun = S("cmsdoctor/lbl_lastrun"),
            btn_runall = S("cmsdoctor/btn_runall"),
            btn_running = S("cmsdoctor/btn_running"),
            sum_healthy = S("cmsdoctor/sum_healthy"),
            sum_warnings = S("cmsdoctor/sum_warnings"),
            sum_faults = S("cmsdoctor/sum_faults"),
            sum_notchecked = S("cmsdoctor/sum_notchecked"),
            tag_all = S("cmsdoctor/tag_all"),
            status_ok = S("cmsdoctor/status_ok"),
            status_warning = S("cmsdoctor/status_warning"),
            status_badpractice = S("cmsdoctor/status_badpractice"),
            status_fault = S("cmsdoctor/status_fault"),
            status_performance = S("cmsdoctor/status_performance"),
            status_notchecked = S("cmsdoctor/status_notchecked"),
            btn_run = S("cmsdoctor/btn_run"),
            btn_fix = S("cmsdoctor/btn_fix"),
            btn_details = S("cmsdoctor/btn_details"),
            btn_dismiss = S("cmsdoctor/btn_dismiss"),
            btn_restore = S("cmsdoctor/btn_restore"),
            dlg_result = S("cmsdoctor/dlg_result"),
            dlg_details = S("cmsdoctor/dlg_details"),
            dlg_categories = S("cmsdoctor/dlg_categories"),
            dlg_checked = S("cmsdoctor/dlg_checked"),
            btn_applyfix = S("cmsdoctor/btn_applyfix"),
            btn_rerun = S("cmsdoctor/btn_rerun"),
            btn_close = S("cmsdoctor/btn_close"),
            confirm_applyfix = S("cmsdoctor/confirm_applyfix"),
            confirm_fix = S("cmsdoctor/confirm_fix")
        },
        contenttypeaudit = new
        {
            alert_running = S("contenttypeaudit/alert_running"),
            alert_notrun = S("contenttypeaudit/alert_notrun"),
            alert_old = S("contenttypeaudit/alert_old"),
            alert_started = S("contenttypeaudit/alert_started"),
            btn_refresh = S("contenttypeaudit/btn_refresh"),
            btn_runnow = S("contenttypeaudit/btn_runnow"),
            btn_starting = S("contenttypeaudit/btn_starting"),
            btn_failed = S("contenttypeaudit/btn_failed"),
            stat_contenttypes = S("contenttypeaudit/stat_contenttypes"),
            stat_systemtypes = S("contenttypeaudit/stat_systemtypes"),
            stat_orphaned = S("contenttypeaudit/stat_orphaned"),
            stat_unused = S("contenttypeaudit/stat_unused"),
            stat_showing = S("contenttypeaudit/stat_showing"),
            lbl_search = S("contenttypeaudit/lbl_search"),
            opt_allbases = S("contenttypeaudit/opt_allbases"),
            chk_showsystem = S("contenttypeaudit/chk_showsystem"),
            btn_table = S("contenttypeaudit/btn_table"),
            btn_tree = S("contenttypeaudit/btn_tree"),
            btn_export = S("contenttypeaudit/btn_export"),
            col_name = S("contenttypeaudit/col_name"),
            col_base = S("contenttypeaudit/col_base"),
            col_group = S("contenttypeaudit/col_group"),
            col_properties = S("contenttypeaudit/col_properties"),
            col_content = S("contenttypeaudit/col_content"),
            opt_all = S("contenttypeaudit/opt_all"),
            badge_system = S("contenttypeaudit/badge_system"),
            badge_orphaned = S("contenttypeaudit/badge_orphaned")
        },
        linkchecker = new
        {
            alert_running = S("linkchecker/alert_running"),
            alert_notrun = S("linkchecker/alert_notrun"),
            alert_lastran = S("linkchecker/alert_lastran"),
            alert_started = S("linkchecker/alert_started"),
            btn_refresh = S("linkchecker/btn_refresh"),
            btn_runnow = S("linkchecker/btn_runnow"),
            btn_starting = S("linkchecker/btn_starting"),
            btn_failed = S("linkchecker/btn_failed"),
            btn_export = S("linkchecker/btn_export"),
            stat_total = S("linkchecker/stat_total"),
            stat_broken = S("linkchecker/stat_broken"),
            stat_valid = S("linkchecker/stat_valid"),
            stat_internal = S("linkchecker/stat_internal"),
            stat_external = S("linkchecker/stat_external"),
            lbl_search = S("linkchecker/lbl_search"),
            opt_alltypes = S("linkchecker/opt_alltypes"),
            opt_internal = S("linkchecker/opt_internal"),
            opt_external = S("linkchecker/opt_external"),
            opt_allstatus = S("linkchecker/opt_allstatus"),
            opt_brokenonly = S("linkchecker/opt_brokenonly"),
            opt_validonly = S("linkchecker/opt_validonly"),
            col_status = S("linkchecker/col_status"),
            col_url = S("linkchecker/col_url"),
            col_type = S("linkchecker/col_type"),
            col_foundin = S("linkchecker/col_foundin"),
            col_checked = S("linkchecker/col_checked"),
            cell_usedon = S("linkchecker/cell_usedon")
        },
        securityaudit = new
        {
            tab_tree = S("securityaudit/tab_tree"),
            tab_roles = S("securityaudit/tab_roles"),
            tab_issues = S("securityaudit/tab_issues"),
            banner_nodata = S("securityaudit/banner_nodata"),
            banner_runjob = S("securityaudit/banner_runjob"),
            banner_started = S("securityaudit/banner_started"),
            alert_old = S("securityaudit/alert_old"),
            btn_runnow = S("securityaudit/btn_runnow"),
            btn_starting = S("securityaudit/btn_starting"),
            btn_refresh = S("securityaudit/btn_refresh"),
            btn_failed = S("securityaudit/btn_failed"),
            stat_analyzed = S("securityaudit/stat_analyzed"),
            stat_roles = S("securityaudit/stat_roles"),
            stat_issues = S("securityaudit/stat_issues"),
            stat_lastanalysis = S("securityaudit/stat_lastanalysis"),
            pager_previous = S("securityaudit/pager_previous"),
            pager_info = S("securityaudit/pager_info"),
            pager_next = S("securityaudit/pager_next")
        },
        bulkeditor = new
        {
            opt_selecttype = S("bulkeditor/opt_selecttype"),
            btn_columns = S("bulkeditor/btn_columns"),
            btn_addfilter = S("bulkeditor/btn_addfilter"),
            chk_includereferences = S("bulkeditor/chk_includereferences"),
            btn_applyfilters = S("bulkeditor/btn_applyfilters"),
            empty_selecttype = S("bulkeditor/empty_selecttype"),
            lbl_perpage = S("bulkeditor/lbl_perpage"),
            pending_count = S("bulkeditor/pending_count"),
            btn_discardall = S("bulkeditor/btn_discardall"),
            btn_saveall = S("bulkeditor/btn_saveall"),
            btn_publishall = S("bulkeditor/btn_publishall"),
            confirm_discard = S("bulkeditor/confirm_discard")
        },
        contentstatistics = new
        {
            banner_runjob = S("contentstatistics/banner_runjob"),
            btn_runnow = S("contentstatistics/btn_runnow"),
            btn_starting = S("contentstatistics/btn_starting"),
            error_load = S("contentstatistics/error_load"),
            error_render = S("contentstatistics/error_render"),
            chart_byctype = S("contentstatistics/chart_byctype"),
            chart_bystatus = S("contentstatistics/chart_bystatus"),
            chart_created = S("contentstatistics/chart_created"),
            chart_staleness = S("contentstatistics/chart_staleness"),
            chart_editoractivity = S("contentstatistics/chart_editoractivity"),
            stat_totalcontent = S("contentstatistics/stat_totalcontent"),
            stat_published = S("contentstatistics/stat_published"),
            stat_draft = S("contentstatistics/stat_draft"),
            stat_editors = S("contentstatistics/stat_editors"),
            stat_pages = S("contentstatistics/stat_pages"),
            stat_blocks = S("contentstatistics/stat_blocks"),
            stat_media = S("contentstatistics/stat_media")
        },
        activitytimeline = new
        {
            stat_today = S("activitytimeline/stat_today"),
            stat_activeeditors = S("activitytimeline/stat_activeeditors"),
            stat_publishes = S("activitytimeline/stat_publishes"),
            stat_drafts = S("activitytimeline/stat_drafts"),
            opt_allusers = S("activitytimeline/opt_allusers"),
            opt_published = S("activitytimeline/opt_published"),
            opt_draft = S("activitytimeline/opt_draft"),
            opt_readytopublish = S("activitytimeline/opt_readytopublish"),
            opt_scheduled = S("activitytimeline/opt_scheduled"),
            opt_rejected = S("activitytimeline/opt_rejected"),
            opt_previouslypublished = S("activitytimeline/opt_previouslypublished"),
            opt_comment = S("activitytimeline/opt_comment"),
            opt_allcontenttypes = S("activitytimeline/opt_allcontenttypes"),
            btn_filter = S("activitytimeline/btn_filter"),
            btn_clear = S("activitytimeline/btn_clear"),
            banner_showingfor = S("activitytimeline/banner_showingfor"),
            btn_showall = S("activitytimeline/btn_showall")
        },
        personalizationaudit = new
        {
            alert_running = S("personalizationaudit/alert_running"),
            alert_notrun = S("personalizationaudit/alert_notrun"),
            alert_old = S("personalizationaudit/alert_old"),
            btn_runnow = S("personalizationaudit/btn_runnow"),
            btn_refresh = S("personalizationaudit/btn_refresh"),
            btn_starting = S("personalizationaudit/btn_starting"),
            stat_total = S("personalizationaudit/stat_total"),
            stat_content = S("personalizationaudit/stat_content"),
            stat_groups = S("personalizationaudit/stat_groups"),
            lbl_search = S("personalizationaudit/lbl_search"),
            lbl_type = S("personalizationaudit/lbl_type"),
            lbl_group = S("personalizationaudit/lbl_group"),
            opt_alltypes = S("personalizationaudit/opt_alltypes"),
            opt_allgroups = S("personalizationaudit/opt_allgroups"),
            col_content = S("personalizationaudit/col_content"),
            col_type = S("personalizationaudit/col_type"),
            col_groups = S("personalizationaudit/col_groups"),
            col_location = S("personalizationaudit/col_location")
        },
        audiencemanager = new
        {
            stat_audiences = S("audiencemanager/stat_audiences"),
            stat_withstats = S("audiencemanager/stat_withstats"),
            stat_categories = S("audiencemanager/stat_categories"),
            stat_totalcriteria = S("audiencemanager/stat_totalcriteria"),
            stat_showing = S("audiencemanager/stat_showing"),
            lbl_search = S("audiencemanager/lbl_search"),
            opt_allcategories = S("audiencemanager/opt_allcategories"),
            chk_hasstats = S("audiencemanager/chk_hasstats"),
            lnk_personalizationaudit = S("audiencemanager/lnk_personalizationaudit"),
            btn_export = S("audiencemanager/btn_export"),
            col_name = S("audiencemanager/col_name"),
            col_criteria = S("audiencemanager/col_criteria"),
            col_operator = S("audiencemanager/col_operator"),
            col_statistics = S("audiencemanager/col_statistics"),
            col_usage = S("audiencemanager/col_usage"),
            opt_all = S("audiencemanager/opt_all"),
            title_usagedetails = S("audiencemanager/title_usagedetails"),
            title_notused = S("audiencemanager/title_notused"),
            title_runjobfirst = S("audiencemanager/title_runjobfirst")
        },
        contentimporter = new
        {
            step_upload = S("contentimporter/step_upload"),
            step_configure = S("contentimporter/step_configure"),
            step_dryrun = S("contentimporter/step_dryrun"),
            step_import = S("contentimporter/step_import"),
            lbl_dropfile = S("contentimporter/lbl_dropfile"),
            btn_browse = S("contentimporter/btn_browse"),
            lbl_contenttype = S("contentimporter/lbl_contenttype"),
            lbl_language = S("contentimporter/lbl_language"),
            lbl_parent = S("contentimporter/lbl_parent"),
            lbl_namecol = S("contentimporter/lbl_namecol"),
            lbl_publishafter = S("contentimporter/lbl_publishafter"),
            lbl_selectparent = S("contentimporter/lbl_selectparent"),
            btn_next = S("contentimporter/btn_next"),
            btn_back = S("contentimporter/btn_back"),
            lbl_mapping = S("contentimporter/lbl_mapping"),
            lbl_sourcecol = S("contentimporter/lbl_sourcecol"),
            lbl_targetfield = S("contentimporter/lbl_targetfield"),
            opt_skip = S("contentimporter/opt_skip"),
            btn_dryrun = S("contentimporter/btn_dryrun"),
            lbl_dryresult = S("contentimporter/lbl_dryresult"),
            btn_import = S("contentimporter/btn_import"),
            btn_startover = S("contentimporter/btn_startover"),
            lbl_importing = S("contentimporter/lbl_importing")
        },
        managechildren = new
        {
            lbl_selectparent = S("managechildren/lbl_selectparent"),
            btn_selectparent = S("managechildren/btn_selectparent"),
            btn_sortaz = S("managechildren/btn_sortaz"),
            btn_sortza = S("managechildren/btn_sortza"),
            btn_sortbydate = S("managechildren/btn_sortbydate"),
            btn_publishall = S("managechildren/btn_publishall"),
            btn_unpublishall = S("managechildren/btn_unpublishall"),
            btn_deleteselected = S("managechildren/btn_deleteselected"),
            btn_saveorder = S("managechildren/btn_saveorder"),
            col_name = S("managechildren/col_name"),
            col_status = S("managechildren/col_status"),
            col_changed = S("managechildren/col_changed"),
            col_type = S("managechildren/col_type"),
            confirm_delete = S("managechildren/confirm_delete"),
            confirm_publishall = S("managechildren/confirm_publishall"),
            confirm_unpublishall = S("managechildren/confirm_unpublishall")
        },
        recommendations = new
        {
            banner_info = S("recommendations/banner_info"),
            btn_addrule = S("recommendations/btn_addrule"),
            col_parenttype = S("recommendations/col_parenttype"),
            col_allowedtypes = S("recommendations/col_allowedtypes"),
            col_actions = S("recommendations/col_actions"),
            dlg_addrule = S("recommendations/dlg_addrule"),
            dlg_editrule = S("recommendations/dlg_editrule"),
            lbl_parenttype = S("recommendations/lbl_parenttype"),
            lbl_allowedtypes = S("recommendations/lbl_allowedtypes"),
            btn_save = S("recommendations/btn_save"),
            btn_cancel = S("recommendations/btn_cancel"),
            btn_edit = S("recommendations/btn_edit"),
            btn_delete = S("recommendations/btn_delete"),
            empty_norules = S("recommendations/empty_norules"),
            confirm_delete = S("recommendations/confirm_delete")
        },
        gantt = new
        {
            error_load = S("gantt/error_load"),
            empty_nojobs = S("gantt/empty_nojobs"),
            stat_totaljobs = S("gantt/stat_totaljobs"),
            stat_enabled = S("gantt/stat_enabled"),
            stat_running = S("gantt/stat_running"),
            stat_executions = S("gantt/stat_executions"),
            btn_previous = S("gantt/btn_previous"),
            btn_today = S("gantt/btn_today"),
            btn_next = S("gantt/btn_next"),
            lbl_viewhours = S("gantt/lbl_viewhours"),
            col_job = S("gantt/col_job")
        },
        activeeditors = new
        {
            error_nosignalr = S("activeeditors/error_nosignalr"),
            error_connect = S("activeeditors/error_connect"),
            stat_online = S("activeeditors/stat_online"),
            stat_editing = S("activeeditors/stat_editing"),
            stat_today = S("activeeditors/stat_today"),
            section_online = S("activeeditors/section_online"),
            section_today = S("activeeditors/section_today"),
            lbl_connected = S("activeeditors/lbl_connected"),
            btn_sendmessage = S("activeeditors/btn_sendmessage"),
            badge_you = S("activeeditors/badge_you"),
            badge_offline = S("activeeditors/badge_offline"),
            chat_title = S("activeeditors/chat_title"),
            chat_empty = S("activeeditors/chat_empty"),
            chat_placeholder = S("activeeditors/chat_placeholder"),
            dlg_sendmessage = S("activeeditors/dlg_sendmessage"),
            dlg_desc = S("activeeditors/dlg_desc"),
            dlg_placeholder = S("activeeditors/dlg_placeholder"),
            btn_cancel = S("activeeditors/btn_cancel"),
            btn_send = S("activeeditors/btn_send"),
            btn_sending = S("activeeditors/btn_sending"),
            msg_sent = S("activeeditors/msg_sent")
        },
        components = new
        {
            picker_title = S("components/picker_title"),
            picker_search = S("components/picker_search"),
            picker_noresults = S("components/picker_noresults"),
            btn_cancel = S("components/btn_cancel"),
            btn_select = S("components/btn_select"),
            typepicker_title = S("components/typepicker_title"),
            typepicker_search = S("components/typepicker_search"),
            typepicker_noresults = S("components/typepicker_noresults")
        },
        editorpowertools = new
        {
            loading = S("editorpowertools/loading"),
            noresults = S("editorpowertools/noresults")
        }
    };
}
